Repository SSUMC-6th/iOS_A, pull requests merged in 2024-05, with the labels that each got.

#38 [JC/Week4] Token & UserDefaults
  jc/Week4_Mission/Week4_Mission.xcodeproj/project.pbxproj
  jc/Week4_Mission/Week4_Mission.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  jc/Week4_Mission/Week4_Mission.xcodeproj/xcshareddata/xcschemes/Week4_Mission.xcscheme
  jc/Week4_Mission/Week4_Mission/EmailAuthViewController/MainViewController.swift
  jc/Week4_Mission/Week4_Mission/EmailAuthViewController/ProfileLoginedViewController.swift
  jc/Week4_Mission/Week4_Mission/GoogleAuthViewController/GoogleAuthLoginedViewController.swift
  jc/Week4_Mission/Week4_Mission/GoogleAuthViewController/GoogleAuthViewController.swift
  jc/Week4_Mission/Week4_Mission/GoogleService-Info.plist
  jc/Week4_Mission/Week4_Mission/Info.plist
  jc/Week4_Mission/Week4_Mission/MainViewController.swift
  jc/Week4_Mission/Week4_Mission/ProfileViewController.swift
  jc/Week4_Mission/Week4_Mission/Source/AppDelegate.swift
  jc/Week4_Mission/Week4_Mission/Source/SceneDelegate.swift
  jc/Week5_Mission/Week5_Mission.xcodeproj/project.pbxproj
  jc/Week5_Mission/Week5_Mission.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: ch4

#44 [JC/Week5] Network
  jc/Week5_Mission/Week5_Mission/ViewController/MainViewController.swift
Labels: ch5

#46 [eddy/week4] Token & UserDefaults
  eddy/iOS_study_week1/iOS_study_week1.xcodeproj/project.pbxproj
  eddy/iOS_study_week1/iOS_study_week1/AppDelegate.swift
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/mainBackground.colorset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/mainTopBanner.colorset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/my배민.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/my배민.imageset/my배민.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/검색.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/검색.imageset/검색.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/광고1.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/광고1.imageset/광고1.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/광고2.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/광고2.imageset/광고2.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/리스트.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/리스트.imageset/리스트.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/메인.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/메인.imageset/메인.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/버튼1.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/버튼1.imageset/버튼1.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/버튼2.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/버튼2.imageset/버튼3.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/버튼3.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/버튼3.imageset/버튼2.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/주문내역.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/주문내역.imageset/주문내역.png
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/찜.imageset/Contents.json
  eddy/iOS_study_week1/iOS_study_week1/Assets.xcassets/찜.imageset/찜.png
  eddy/iOS_study_week1/iOS_study_week1/Info.plist
  eddy/iOS_study_week1/iOS_study_week1/SceneDelegate.swift
  eddy/iOS_study_week1/iOS_study_week1/ViewController.swift
  eddy/iOS_study_week1/iOS_study_week1Tests/iOS_study_week1Tests.swift
  eddy/iOS_study_week1/iOS_study_week1UITests/iOS_study_week1UITests.swift
  eddy/iOS_study_week1/iOS_study_week1UITests/iOS_study_week1UITestsLaunchTests.swift
  eddy/iOS_study_week4/iOS_study_week4/ViewController.swift
  eddy/iOS_study_week5/iOS_study_week5.xcodeproj/project.pbxproj
  eddy/iOS_study_week5/iOS_study_week5/AppDelegate.swift
  eddy/iOS_study_week5/iOS_study_week5/ContentView.swift
  eddy/iOS_study_week5/iOS_study_week5/Info.plist
  eddy/iOS_study_week5/iOS_study_week5/SceneDelegate.swift
  eddy/iOS_study_week5/iOS_study_week5/ViewController.swift
  eddy/iOS_study_week5/iOS_study_week5/request.swift
  eddy/iOS_study_week5/iOS_study_week5Tests/iOS_study_week5Tests.swift
  eddy/iOS_study_week5/iOS_study_week5UITests/iOS_study_week5UITests.swift
  eddy/iOS_study_week5/iOS_study_week5UITests/iOS_study_week5UITestsLaunchTests.swift
Labels: ch4

#47 [Cookie/week5] Network(2)
  cookie/cookie_week5/Podfile.lock
  cookie/cookie_week5/cookie_week5.xcodeproj/project.pbxproj
  cookie/cookie_week5/cookie_week5.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  cookie/cookie_week5/cookie_week5.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  cookie/cookie_week5/cookie_week5.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  cookie/cookie_week5/cookie_week5.xcworkspace/contents.xcworkspacedata
  cookie/cookie_week5/cookie_week5.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  cookie/cookie_week5/cookie_week5/AppDelegate.swift
  cookie/cookie_week5/cookie_week5/Assets.xcassets/AccentColor.colorset/Contents.json
  cookie/cookie_week5/cookie_week5/Assets.xcassets/AppIcon.appiconset/Contents.json
  cookie/cookie_week5/cookie_week5/Assets.xcassets/Contents.json
  cookie/cookie_week5/cookie_week5/Info.plist
  cookie/cookie_week5/cookie_week5/SceneDelegate.swift
  cookie/cookie_week5/cookie_week5/ViewController.swift
  cookie/cookie_week5/cookie_week5/WeatherApp.gif
  cookie/cookie_week5/cookie_week5/WeatherData.swift
Labels: ch5

#42 [JC/Week6] Layout with SwiftUI
  jc/Week6_Mission/Week6_Mission.xcodeproj/project.pbxproj
  jc/Week6_Mission/Week6_Mission.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  jc/Week6_Mission/Week6_Mission.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  jc/Week6_Mission/Week6_Mission.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  jc/Week6_Mission/Week6_Mission.xcodeproj/xcshareddata/xcschemes/Week6_Mission.xcscheme
  jc/Week6_Mission/Week6_Mission/Assets.xcassets/AccentColor.colorset/Contents.json
  jc/Week6_Mission/Week6_Mission/Assets.xcassets/AppIcon.appiconset/Contents.json
  jc/Week6_Mission/Week6_Mission/Assets.xcassets/Contents.json
  jc/Week6_Mission/Week6_Mission/ContentView.swift
  jc/Week6_Mission/Week6_Mission/HomeViewSubViews/AdBannerView.swift
  jc/Week6_Mission/Week6_Mission/HomeViewSubViews/BigSaleView.swift
  jc/Week6_Mission/Week6_Mission/HomeViewSubViews/CouponBannerView.swift
  jc/Week6_Mission/Week6_Mission/HomeViewSubViews/ThreeTabSubViews/DeliveryView.swift
  jc/Week6_Mission/Week6_Mission/HomeViewSubViews/ThreeTabSubViews/LowPriceDelivery.swift
  jc/Week6_Mission/Week6_Mission/HomeViewSubViews/ThreeTabSubViews/StoreView.swift
  jc/Week6_Mission/Week6_Mission/HomeViewSubViews/ThreeTabsView.swift
  jc/Week6_Mission/Week6_Mission/HomeViewSubViews/TopInfoView.swift
  jc/Week6_Mission/Week6_Mission/Preview Content/Preview Assets.xcassets/Contents.json
  jc/Week6_Mission/Week6_Mission/TabBarView/HomeView.swift
  jc/Week6_Mission/Week6_Mission/TabBarView/MyPageView.swift
  jc/Week6_Mission/Week6_Mission/TabBarView/MyView.swift
  jc/Week6_Mission/Week6_Mission/TabBarView/OrderView.swift
  jc/Week6_Mission/Week6_Mission/TabBarView/SearchView.swift
  jc/Week6_Mission/Week6_Mission/Week6_Mission.entitlements
  jc/Week6_Mission/Week6_Mission/Week6_MissionApp.swift
Labels: ch6

#51 [Baki/week6] Layout(2)
  baki/.DS_Store
  baki/.gitignore
  baki/baki_week3/.DS_Store
  baki/baki_week6/baki_week6/baki_week6.xcodeproj/project.pbxproj
  baki/baki_week6/baki_week6/baki_week6.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  baki/baki_week6/baki_week6/baki_week6.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  baki/baki_week6/baki_week6/baki_week6.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/AccentColor.colorset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/AppIcon.appiconset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/cf.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/cf.imageset/스크린샷 2024-05-20 오전 12.36.38.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage1.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage1.imageset/스크린샷 2024-04-09 오후 2.51.51.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage10.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage10.imageset/스크린샷 2024-04-09 오후 2.52.39.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage2.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage2.imageset/스크린샷 2024-04-09 오후 2.51.59.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage3.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage3.imageset/스크린샷 2024-04-09 오후 2.52.04.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage4.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage4.imageset/스크린샷 2024-04-09 오후 2.52.09.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage5.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage5.imageset/스크린샷 2024-04-09 오후 2.52.13.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage6.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage6.imageset/스크린샷 2024-04-09 오후 2.52.17.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage7.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage7.imageset/스크린샷 2024-04-09 오후 2.52.21.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage8.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage8.imageset/스크린샷 2024-04-09 오후 2.52.26.png
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage9.imageset/Contents.json
  baki/baki_week6/baki_week6/baki_week6/Assets.xcassets/menuimage9.imageset/스크린샷 2024-04-09 오후 2.52.30.png
  baki/baki_week6/baki_week6/baki_week6/HeartView.swift
  baki/baki_week6/baki_week6/baki_week6/MainTabView.swift
  baki/baki_week6/baki_week6/baki_week6/MenuView.swift
  baki/baki_week6/baki_week6/baki_week6/MyView.swift
  baki/baki_week6/baki_week6/baki_week6/Preview Content/Preview Assets.xcassets/Contents.json
  baki/baki_week6/baki_week6/baki_week6/SearchView.swift
  baki/baki_week6/baki_week6/baki_week6/baeminView.swift
  baki/baki_week6/baki_week6/baki_week6/baki_week6App.swift
Labels: ch6

#49 [JC/Week7] Vertical & Horizontal ScrollView 구현 완료
  jc/Week7_Mission/Week7_Mission.xcodeproj/project.pbxproj
  jc/Week7_Mission/Week7_Mission.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  jc/Week7_Mission/Week7_Mission.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  jc/Week7_Mission/Week7_Mission.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  jc/Week7_Mission/Week7_Mission.xcodeproj/xcshareddata/xcschemes/Week7_Mission.xcscheme
  jc/Week7_Mission/Week7_Mission/Assets.xcassets/AccentColor.colorset/Contents.json
  jc/Week7_Mission/Week7_Mission/Assets.xcassets/AppIcon.appiconset/Contents.json
  jc/Week7_Mission/Week7_Mission/Assets.xcassets/Contents.json
  jc/Week7_Mission/Week7_Mission/Assets.xcassets/jc.imageset/Contents.json
  jc/Week7_Mission/Week7_Mission/Assets.xcassets/jc.imageset/jc.png
  jc/Week7_Mission/Week7_Mission/ChattingView.swift
  jc/Week7_Mission/Week7_Mission/ContentView.swift
  jc/Week7_Mission/Week7_Mission/HomeView/DataType.swift
  jc/Week7_Mission/Week7_Mission/HomeView/HomeView.swift
  jc/Week7_Mission/Week7_Mission/MyPageView.swift
  jc/Week7_Mission/Week7_Mission/NearMeView.swift
  jc/Week7_Mission/Week7_Mission/OurTownView.swift
  jc/Week7_Mission/Week7_Mission/Preview Content/Preview Assets.xcassets/Contents.json
  jc/Week7_Mission/Week7_Mission/Week7_Mission.entitlements
  jc/Week7_Mission/Week7_Mission/Week7_MissionApp.swift
Labels: ch7

#53 [Baki/week7] List & ScrollView(2)
  baki/baki_week7/baki_week7.xcodeproj/project.pbxproj
  baki/baki_week7/baki_week7.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  baki/baki_week7/baki_week7.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  baki/baki_week7/baki_week7.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  baki/baki_week7/baki_week7/Assets.xcassets/AccentColor.colorset/Contents.json
  baki/baki_week7/baki_week7/Assets.xcassets/AppIcon.appiconset/Contents.json
  baki/baki_week7/baki_week7/Assets.xcassets/Contents.json
  baki/baki_week7/baki_week7/Assets.xcassets/air.imageset/Contents.json
  baki/baki_week7/baki_week7/Assets.xcassets/air.imageset/스크린샷 2024-05-27 오전 12.35.24.png
  baki/baki_week7/baki_week7/Assets.xcassets/airmax.imageset/Contents.json
  baki/baki_week7/baki_week7/Assets.xcassets/airmax.imageset/스크린샷 2024-05-27 오전 1.02.48.png
  baki/baki_week7/baki_week7/Assets.xcassets/airmax2.imageset/Contents.json
  baki/baki_week7/baki_week7/Assets.xcassets/airmax2.imageset/스크린샷 2024-05-27 오전 1.13.29.png
  baki/baki_week7/baki_week7/Assets.xcassets/my.imageset/Contents.json
  baki/baki_week7/baki_week7/Assets.xcassets/my.imageset/스크린샷 2024-05-27 오전 1.14.55.png
  baki/baki_week7/baki_week7/ContentView.swift
  baki/baki_week7/baki_week7/PostView.swift
  baki/baki_week7/baki_week7/Preview Content/Preview Assets.xcassets/Contents.json
  baki/baki_week7/baki_week7/baki_week7App.swift
  baki/baki_week7/baki_week7/mainTabview.swift
  baki/baki_week7/baki_week7/menuStruct.swift
  baki/baki_week7/baki_week7/secondPostView.swift
  baki/baki_week7/baki_week7/secondView.swift
  baki/baki_week7/baki_week7/secondmenuStruct.swift
Labels: ch7
